# Generated by Django 5.1 on 2024-09-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_contacto_delete_entregable_delete_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacto',
            new_name='contact',
        ),
    ]
