# Generated by Django 5.1 on 2024-09-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_contacto_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='profesion',
            new_name='empresa',
        ),
    ]
