# Generated by Django 5.1 on 2024-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_profesion_contact_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
